In [12]:
#from PIL import image
#from Tkinter import *
from PIL import Image as Img
from PIL import ImageTk
from keras.applications.vgg16 import preprocess_input
import base64
from io import BytesIO
import json
import random
import cv2
from keras.models import load_model
import numpy as np
from keras.preprocessing import image

model = load_model('facefeatures_new_model.h5')

#loading the cascades
face_cascade = cv2.CascadeClassifier('haarcascade_frontalface_default.xml')

def face_extractor(img):
    #Function detects faces and returns the cropped face
    #If no face detected it returns the input image
    
    faces = face_cascade.detectMultiScale(img, 1.3, 5)
    
    if faces is ():
        return None
    
    #Crop all faces found
    for (x,y,w,h) in faces:
        cv2.rectangle(img, (x,y),(x+w,y+h),(0,255,255),2)
        cropped_face = img[y:y+h, x:x+w]
        
    return cropped_face

#Doing Face Recognition with the webcam
video_capture = cv2.VideoCapture(0)
while True:
    _, frame = video_capture.read()
    
    face=face_extractor(frame)
    if type(face) is np.ndarray:
        face=cv2.resize(face, (224,224))
        im= Img.fromarray(face , 'RGB')
        
        #Resizing because we trained the model with this size
        img_array = np.array(im)
        
        #Keras model used 4D tensor so we change the dimension from 128x128x3 to 1x128x128x3
        img_array = np.expand_dims(img_array, axis=0)
        pred = model.predict(img_array)
        print(pred)
        
        
        name= "It's not you"
        #name=""
        if(pred[0][0]>0.9):
            name="Hiren"
            #cv2.putText(frame,name, (50,50), cv2.FONT_HERSHEY_COMPLEX, 1, (0,255,0),2)
        cv2.putText(frame,name, (50,50), cv2.FONT_HERSHEY_COMPLEX, 1, (0,255,0),2)
    else:
        
        cv2.putText(frame,"No Face Found", (50,50), cv2.FONT_HERSHEY_COMPLEX, 1, (0,255,0),2)
    cv2.imshow('Video',frame)
    #if cv2.waitKey(1) & 0xFF == ord('q'):
    if cv2.waitKey(1) == 13:
        break
video.capture.release()
cv2.destroyAllWindows()

[[1.2909544e-24 1.0000000e+00]]
[[8.130393e-27 1.000000e+00]]
[[9.135469e-25 1.000000e+00]]
[[1.2532447e-20 1.0000000e+00]]
[[3.47488e-22 1.00000e+00]]
[[1.3190931e-20 1.0000000e+00]]
[[1.101093e-20 1.000000e+00]]
[[6.0274845e-22 1.0000000e+00]]
[[1.1982537e-17 1.0000000e+00]]
[[9.352955e-20 1.000000e+00]]
[[1.5427523e-13 1.0000000e+00]]
[[8.936741e-21 1.000000e+00]]
[[1.4373375e-16 1.0000000e+00]]
[[1.8352758e-19 1.0000000e+00]]
[[3.2827668e-22 1.0000000e+00]]
[[2.2280513e-17 1.0000000e+00]]
[[1.2163372e-20 1.0000000e+00]]
[[2.4774716e-14 1.0000000e+00]]
[[2.5601915e-16 1.0000000e+00]]
[[1.9083722e-17 1.0000000e+00]]
[[1.5619183e-16 1.0000000e+00]]
[[3.9671367e-14 1.0000000e+00]]
[[1.4321941e-14 1.0000000e+00]]
[[5.993612e-17 1.000000e+00]]
[[2.8163368e-18 1.0000000e+00]]
[[4.204127e-13 1.000000e+00]]
[[1.4530128e-13 1.0000000e+00]]
[[2.815484e-21 1.000000e+00]]
[[4.2937334e-16 1.0000000e+00]]
[[4.767718e-13 1.000000e+00]]
[[2.6866471e-20 1.0000000e+00]]
[[4.591296e-15 1.000000e+00]]


[[1.0000000e+00 2.6915534e-14]]
[[1.0000000e+00 6.0335487e-10]]
[[1.0000000e+00 1.7801463e-13]]
[[1.0000000e+00 7.0971614e-13]]
[[1.2143306e-11 1.0000000e+00]]
[[0.956896   0.04310396]]
[[1.3770348e-04 9.9986231e-01]]
[[1.000000e+00 3.441818e-08]]
[[0.9870661  0.01293385]]
[[0.01486844 0.98513156]]
[[0.00341264 0.9965874 ]]
[[0.5769328 0.4230672]]
[[0.99404234 0.00595769]]
[[0.78818583 0.21181424]]
[[0.9896254  0.01037463]]
[[9.9999475e-01 5.2094529e-06]]
[[0.76161766 0.23838226]]
[[0.13624074 0.8637593 ]]
[[0.96610796 0.03389206]]
[[0.99694914 0.00305084]]
[[1.2948952e-09 1.0000000e+00]]
[[1.16418975e-11 1.00000000e+00]]
[[0.00199126 0.9980088 ]]
[[6.2479226e-06 9.9999380e-01]]
[[7.3166791e-04 9.9926835e-01]]
[[0.09397987 0.9060201 ]]
[[2.1007628e-04 9.9978989e-01]]
[[9.995802e-01 4.197819e-04]]
[[9.999919e-01 8.109359e-06]]
[[1.256447e-05 9.999875e-01]]
[[0.01377457 0.9862255 ]]
[[0.00428189 0.99571806]]
[[0.15525164 0.8447484 ]]
[[2.2734625e-12 1.0000000e+00]]
[[3.849959e-05 9.99961

[[1.000000e+00 8.294902e-14]]
[[1.000000e+00 6.783914e-12]]
[[1.0000000e+00 3.7675844e-17]]
[[1.0000000e+00 1.9701912e-16]]
[[1.000000e+00 7.910683e-23]]
[[1.0000000e+00 7.8560454e-22]]
[[1.0000000e+00 1.3727209e-16]]
[[1.00000000e+00 1.38417105e-27]]
[[1.000000e+00 5.937228e-15]]
[[1.000000e+00 8.265612e-20]]
[[1.0000000e+00 2.1123132e-15]]
[[1.0000000e+00 5.1729528e-12]]
[[1.0000000e+00 4.2321853e-15]]
[[1.0000000e+00 1.0474299e-18]]
[[1.0000000e+00 2.8263337e-19]]
[[1.0000000e+00 6.1626936e-26]]
[[1.000000e+00 4.816551e-18]]
[[1.0000000e+00 4.4687478e-23]]
[[1.0000000e+00 2.6464707e-18]]
[[1.0000000e+00 2.7443716e-11]]
[[1.00000e+00 4.68885e-18]]
[[1.0000000e+00 4.2140167e-21]]
[[1.0000000e+00 4.6074004e-12]]
[[1.0000000e+00 1.0839469e-14]]
[[1.000000e+00 2.305146e-15]]
[[1.0000000e+00 1.6750731e-13]]
[[1.0000000e+00 1.8260206e-14]]
[[1.0000000e+00 6.4348695e-13]]
[[1.0000000e+00 1.7525066e-14]]
[[1.0000000e+00 2.0181406e-12]]
[[1.0000000e+00 1.4861809e-15]]
[[1.000000e+00 4.587501e

[[0.9870619  0.01293806]]
[[0.43902087 0.5609791 ]]
[[1.0000000e+00 1.7445048e-19]]
[[1.0000000e+00 3.0188976e-17]]
[[1.0000000e+00 1.8192776e-20]]
[[1.0000000e+00 4.8819442e-17]]
[[1.0000000e+00 3.0549618e-09]]
[[0.09366307 0.90633696]]
[[1.000000e+00 1.372212e-10]]
[[1.0000000e+00 1.3473257e-09]]
[[0.71957576 0.28042424]]
[[9.9999893e-01 1.1292159e-06]]
[[0.56261814 0.43738192]]
[[9.9999905e-01 9.6230144e-07]]
[[1.0000000e+00 1.1336405e-09]]
[[9.9999976e-01 2.9600102e-07]]
[[1.0000000e+00 1.1176121e-08]]
[[9.999993e-01 6.968042e-07]]
[[9.9999893e-01 1.0844361e-06]]
[[0.8610594  0.13894057]]
[[9.999982e-01 1.786723e-06]]
[[0.9844363  0.01556374]]
[[1.0000000e+00 5.0343096e-10]]
[[1.000000e+00 7.117887e-10]]
[[1.000000e+00 9.977245e-10]]
[[9.99999881e-01 1.17986346e-07]]
[[9.9999762e-01 2.4221333e-06]]
[[9.9985886e-01 1.4117357e-04]]
[[9.999999e-01 1.519637e-07]]
[[9.999987e-01 1.272438e-06]]
[[9.9999976e-01 2.2767026e-07]]
[[0.9921172  0.00788284]]
[[9.9998832e-01 1.1736775e-05]]
[[9.

[[9.9999988e-01 1.3465267e-07]]
[[1.000000e+00 5.057468e-09]]
[[7.018235e-05 9.999298e-01]]
[[9.9999213e-01 7.8784515e-06]]
[[9.9928135e-01 7.1869657e-04]]
[[4.442883e-13 1.000000e+00]]
[[1.0778537e-12 1.0000000e+00]]
[[8.8793774e-07 9.9999917e-01]]
[[4.5589932e-05 9.9995446e-01]]
[[3.6818562e-07 9.9999964e-01]]
[[0.06318677 0.93681324]]
[[0.89743686 0.10256318]]
[[4.8446677e-06 9.9999511e-01]]
[[0.0040166  0.99598336]]
[[9.9998951e-01 1.0476366e-05]]
[[1.3716155e-10 1.0000000e+00]]
[[2.8692980e-06 9.9999714e-01]]
[[1.8803976e-11 1.0000000e+00]]
[[0.03488781 0.96511215]]
[[1.13496075e-08 1.00000000e+00]]
[[1.407423e-08 1.000000e+00]]
[[0.27297017 0.7270298 ]]
[[9.9992788e-01 7.2075694e-05]]
[[0.8202508  0.17974925]]
[[0.95116204 0.04883802]]
[[0.9840958  0.01590414]]
[[0.9571551  0.04284484]]
[[0.9935201  0.00647996]]
[[9.999151e-01 8.487399e-05]]
[[1.0000000e+00 1.1056142e-11]]
[[0.99563473 0.00436526]]
[[0.96975255 0.03024737]]
[[0.06601676 0.93398327]]
[[0.9876593  0.01234076]]
[[0.

[[0.00214972 0.9978503 ]]
[[0.00140086 0.9985991 ]]
[[9.9992394e-01 7.6063305e-05]]
[[4.5650647e-04 9.9954349e-01]]
[[0.02325996 0.97674006]]
[[0.9733482  0.02665182]]
[[0.9860196  0.01398043]]
[[9.9976152e-01 2.3844278e-04]]
[[0.0110303 0.9889697]]
[[1.0000000e+00 2.3129276e-08]]
[[5.4789012e-08 1.0000000e+00]]
[[1.2057193e-08 1.0000000e+00]]
[[0.990069   0.00993104]]
[[1.0000000e+00 1.7458211e-36]]
[[0.61301595 0.38698402]]
[[1.0000000e+00 3.5696483e-18]]
[[0.7226444  0.27735564]]
[[1.3082337e-07 9.9999988e-01]]
[[1.0000000e+00 4.9999294e-09]]
[[7.7522314e-16 1.0000000e+00]]
[[1.0898153e-11 1.0000000e+00]]
[[6.047195e-08 9.999999e-01]]
[[9.936792e-10 1.000000e+00]]
[[1.1316406e-08 1.0000000e+00]]
[[1.2819322e-09 1.0000000e+00]]
[[1.972881e-11 1.000000e+00]]
[[8.8780314e-07 9.9999917e-01]]
[[5.2284204e-09 1.0000000e+00]]
[[2.7274486e-11 1.0000000e+00]]
[[2.3787946e-12 1.0000000e+00]]
[[3.138759e-11 1.000000e+00]]
[[4.4841856e-15 1.0000000e+00]]
[[3.4108162e-15 1.0000000e+00]]
[[1.5540

[[1.0000000e+00 1.5448392e-14]]
[[4.60255e-05 9.99954e-01]]
[[0.0047924 0.9952076]]
[[0.0038587 0.9961414]]
[[0.99725324 0.00274673]]
[[1.2101062e-15 1.0000000e+00]]
[[2.980786e-05 9.999702e-01]]
[[8.534046e-04 9.991466e-01]]
[[9.9982810e-01 1.7182775e-04]]
[[4.9559454e-11 1.0000000e+00]]
[[5.600245e-12 1.000000e+00]]
[[8.1978874e-07 9.9999917e-01]]
[[1.0753983e-04 9.9989247e-01]]
[[9.9999893e-01 1.0524737e-06]]
[[3.8694148e-04 9.9961311e-01]]
[[9.9999976e-01 2.3336534e-07]]
[[4.5506535e-10 1.0000000e+00]]
[[3.3029195e-05 9.9996698e-01]]
[[0.00140424 0.9985958 ]]
[[0.9988092  0.00119082]]
[[0.9989071  0.00109291]]
[[9.9991071e-01 8.9299596e-05]]
[[0.028114  0.9718859]]
[[1.3132344e-08 1.0000000e+00]]
[[9.5282267e-05 9.9990475e-01]]
[[0.00126659 0.99873346]]
[[1.0000000e+00 4.7014545e-20]]
[[1.1569285e-04 9.9988425e-01]]
[[0.2824939 0.7175061]]
[[1.0000000e+00 6.3702616e-19]]
[[1.0000000e+00 1.0703947e-15]]
[[0.21527117 0.78472877]]
[[0.9970988  0.00290118]]
[[0.36044407 0.63955593]]
[[

NameError: name 'video' is not defined